### ISSUE TITLE
Jump to top of post when I close the picture in lightbox

### ISSUE THREAD

**Issue by 1kuxyz** [iamdarkle/fancybox#4]
A post have many pictures, when you open one picture in the middle of the post, Fancybox will work, and you can browse pictures in lightbox. 
But if you close the lightbox, it will jump to top of the post. You have to scroll down to find the disconnected location.

**Comment by iamdarkle** [comment]
I can confirm the behaviour you are referring to, I don't know exactly what is the cause... 🤔
